// One-off generator: Natural Earth 110m countries GeoJSON -> projected SVG paths.
// Equirectangular projection so country borders and lat/long city pins share the
// exact same linear mapping (see project() in src/data/travel.ts).
//
//   node scripts/build-map.mjs /tmp/world.geojson
//
// Writes src/data/worldPaths.ts. Re-run only if you want to regenerate the map.

import { readFileSync, writeFileSync } from "node:fs";

const INPUT = process.argv[2] ?? "/tmp/world.geojson";
const OUT = new URL("../src/data/worldPaths.ts", import.meta.url);

// Full equirectangular canvas. lon [-180,180] -> x [0,W], lat [90,-90] -> y [0,H].
const W = 1000;
const H = 500;
// Crop the viewBox: drop Antarctica and the empty high Arctic so land fills the frame.
const LAT_TOP = 83;
const LAT_BOTTOM = -56;

const projX = (lon) => ((lon + 180) / 360) * W;
const projY = (lat) => ((90 - lat) / 180) * H;
const r = (n) => Math.round(n * 10) / 10; // 1 decimal place

function ringToPath(ring) {
  let d = "";
  for (let i = 0; i < ring.length; i++) {
    const [lon, lat] = ring[i];
    d += `${i === 0 ? "M" : "L"}${r(projX(lon))} ${r(projY(lat))}`;
  }
  return d + "Z";
}

function featureToPath(geom) {
  const polys =
    geom.type === "Polygon"
      ? [geom.coordinates]
      : geom.type === "MultiPolygon"
        ? geom.coordinates
        : [];
  // Only outer rings — borders read cleaner without lake/hole cutouts at this scale.
  return polys.map((poly) => ringToPath(poly[0])).join("");
}

const fc = JSON.parse(readFileSync(INPUT, "utf8"));
const paths = [];
for (const f of fc.features) {
  const name = f.properties?.NAME ?? f.properties?.SOVEREIGNT ?? "";
  if (name === "Antarctica") continue;
  const d = featureToPath(f.geometry);
  if (d) paths.push(d);
}

const vbY = projY(LAT_TOP);
const vbH = projY(LAT_BOTTOM) - projY(LAT_TOP);
const viewBox = `0 ${r(vbY)} ${W} ${r(vbH)}`;

const body = `// AUTO-GENERATED by scripts/build-map.mjs — do not edit by hand.
// Natural Earth 110m admin-0 countries, equirectangular projection (lon/lat -> x/y).
// ${paths.length} country outlines. Pins are placed with the same projection (project() in ./travel).

export const WORLD_W = ${W};
export const WORLD_H = ${H};
export const WORLD_VIEWBOX = "${viewBox}";

export const WORLD_PATHS: string[] = [
${paths.map((d) => `  ${JSON.stringify(d)},`).join("\n")}
];
`;

writeFileSync(OUT, body);
console.log(
  `Wrote ${OUT.pathname}: ${paths.length} paths, ${(body.length / 1024).toFixed(0)} KB, viewBox="${viewBox}"`,
);
