#!/usr/bin/env python3
"""Build the web photo set + manifest from content/photography/.

Drop any photos (JPG / HEIC / DNG / PNG) into ../content/photography/, run this,
and it will: convert + downsize each to a web JPEG in public/photography/, read
EXIF (focal / aperture / shutter / ISO) for the contact-sheet caption, detect
aspect, and regenerate src/data/photos.ts.

Uses only macOS built-ins (sips, mdls) -- no extra deps.
"""
import os, re, subprocess, sys
from PIL import Image, ExifTags

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)
SRC = os.path.join(SITE, "content", "photography")
OUT = os.path.join(SITE, "public", "photography")
MANIFEST = os.path.join(SITE, "src", "data", "photos.ts")
MAXDIM = 2000          # longest edge, px
QUALITY = 80           # jpeg quality (sips formatOptions)
EXTS = (".jpg", ".jpeg", ".png", ".heic", ".dng")

def sh(args):
    return subprocess.run(args, capture_output=True, text=True).stdout.strip()

def caption(jpg_path):
    """Build a contact-sheet caption from the converted JPEG's EXIF (sips preserves it)."""
    try:
        ifd = Image.open(jpg_path).getexif().get_ifd(ExifTags.IFD.Exif)
    except Exception:
        return ""
    def g(name):
        return next((v for k, v in ifd.items() if ExifTags.TAGS.get(k) == name), None)
    focal = g("FocalLengthIn35mmFilm") or g("FocalLength")
    fnum, exp, iso = g("FNumber"), g("ExposureTime"), g("ISOSpeedRatings")
    parts = []
    if focal:
        try: parts.append(f"{round(float(focal))}mm")
        except (ValueError, TypeError): pass
    if fnum:
        try: parts.append(f"ƒ{round(float(fnum), 1):g}")
        except (ValueError, TypeError): pass
    if exp:
        try:
            e = float(exp)
            parts.append(f"1/{round(1/e)}" if 0 < e < 1 else f"{e:g}s")
        except (ValueError, TypeError): pass
    if iso:
        if isinstance(iso, (tuple, list)): iso = iso[0]
        try: parts.append(f"iso{int(iso)}")
        except (ValueError, TypeError): pass
    return " · ".join(parts)

def dims(path):
    out = sh(["sips", "-g", "pixelWidth", "-g", "pixelHeight", path])
    w = h = 0
    for line in out.splitlines():
        if "pixelWidth" in line: w = int(line.split(":")[1])
        if "pixelHeight" in line: h = int(line.split(":")[1])
    return w, h

def main():
    if not os.path.isdir(SRC):
        sys.exit(f"no source dir: {SRC}")
    os.makedirs(OUT, exist_ok=True)
    files = sorted(f for f in os.listdir(SRC) if f.lower().endswith(EXTS))
    entries = []
    for i, fn in enumerate(files, 1):
        src_path = os.path.join(SRC, fn)
        out_name = f"photo-{i:02d}.jpg"
        out_path = os.path.join(OUT, out_name)
        if not os.path.exists(out_path):
            subprocess.run(["sips", "-s", "format", "jpeg", "-s", "formatOptions",
                            str(QUALITY), "-Z", str(MAXDIM), src_path, "--out", out_path],
                           capture_output=True, text=True)
        if not os.path.exists(out_path):
            print(f"  skip (convert failed): {fn}"); continue
        w, h = dims(out_path)
        aspect = "portrait" if h > w else "landscape"
        cap = caption(out_path)
        num = re.search(r"(\d{3,})", fn)
        exif_id = (num.group(1)[-3:] if num else f"{i:03d}")
        entries.append({"filename": out_name, "src": f"/photography/{out_name}",
                        "alt": "Photograph by Sanjae Suresh", "exifId": exif_id,
                        "exifCaption": cap, "aspect": aspect,
                        "width": w, "height": h})
        print(f"  {fn:48s} -> {out_name}  {w}x{h} {aspect}  [{cap}]")

    lines = ["export interface Photo {",
             "  filename: string;", "  src: string;", "  alt: string;",
             "  exifId: string;", "  exifCaption: string;",
             '  aspect: "landscape" | "portrait";',
             "  width: number;", "  height: number;", "}", "",
             "// Auto-generated by scripts/build-photos.py from content/photography/.",
             "export const photos: Photo[] = ["]
    for e in entries:
        lines.append("  {")
        for k in ("filename", "src", "alt", "exifId", "exifCaption", "aspect",
                  "width", "height"):
            lines.append(f'    {k}: {e[k]!r},'.replace("'", '"'))
        lines.append("  },")
    lines.append("];")
    with open(MANIFEST, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"\nwrote {len(entries)} photos -> {MANIFEST}")

if __name__ == "__main__":
    main()
